Repository hyochan/react-native-nitro-sound, pull requests merged in 2024-06, with the labels that each got.

#609 Add isFinished to rn-playback event
  android/src/main/java/com/dooboolab.audiorecorderplayer/RNAudioRecorderPlayerModule.kt
  index.ts
  ios/RNAudioRecorderPlayer.swift
Labels: 🎯 feature

#611 ci: code-review gpt
  .eslintrc.js
  .github/workflows/code-review.yml
  Example/.eslintrc.js
  Example/.vscode/settings.json
  Example/components/uis/Button.tsx
  Example/package.json
  Example/yarn.lock
  package.json
  yarn.lock
Labels: dependencies, 💨 ci, 🚽 migration, 🝤 refactor

#606 Update README.md
  README.md
Labels: 📖 documentation

#608 Fix race conditions in iOS
  ios/RNAudioRecorderPlayer.swift
Labels: 🛠 bugfix, 📱 iOS

#615 Assign default file extension based on audio format
  android/src/main/java/com/dooboolab.audiorecorderplayer/RNAudioRecorderPlayerModule.kt
  index.ts
  ios/RNAudioRecorderPlayer.swift
Labels: 🍗 enhancement, 🤖 android
